name: webapi CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - webapi/**
  pull_request:
    branches: [ "main" ]
    paths:
      - webapi/**

jobs:

  build_webapi:

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "{{defaultContext}}:${{ secrets.WEB_API }}"
          tags: "${{ secrets.DOCKER_HUB_REPO }}:${{ secrets.WEB_API }}"
